### ISSUE TITLE
Code cleaning 

### ISSUE THREAD

**Issue by Hassnain21** [Ishaan28malik/react-random-user-generator#13]
## Removing unwanted code snippets

**Comment by Ishaan28malik** [comment]
@Hassnain21 go ahead

**Comment by ankurjain00** [comment]
Hi @Ishaan28malik I would like to contribute could you assign it to me

**Comment by Ishaan28malik** [comment]
> Hi @Ishaan28malik I would like to contribute could you assign it to me

Sure.

**Comment by FajarSJ** [comment]
Hi @Ishaan28malik can i contribute, i just want to fix all error and warning in console

**Comment by LuizHAP** [comment]
I remove this codes on #18
