### ISSUE TITLE
Hey  👋

### ISSUE THREAD

**Issue by sell** [Ishaan28malik/react-random-user-generator#14]
You should add a gitignore and add node_modules to it, you should never push node_modules. You should also clear cache so it won't be pushed again, let me know if you need me to make a pr.

**Comment by Ishaan28malik** [comment]
@sell yeah you are correct.

**Comment by ankurjain00** [comment]
Hi @Ishaan28malik I would like to work in the issue

**Comment by sell** [comment]
Hi @ankurjain00 I already fixed.

**Comment by sell** [comment]
@Ishaan28malik How come, you didn't merge mine I removed the node_modules folder as well.

**Comment by Ishaan28malik** [comment]
@sell As node_modules were not supposed to be removed.
