### ISSUE TITLE
Add loading indicator on initial load

### ISSUE THREAD

**Issue by pandurijal** [Ishaan28malik/react-random-user-generator#3]
Hey, at first I thought the app is broken, but I realized it's just because there are no loading indicators on the initial load. Can I work on this issue?

<img width="1280" alt="Screenshot 2020-10-01 at 00 54 48" src="https://user-images.githubusercontent.com/12939625/94721935-c2925800-0380-11eb-94f4-ddb22ad269eb.png">

**Comment by pssingh21** [comment]
Hi. I would like to contribute to this. Happy Hacking!

**Comment by Ishaan28malik** [comment]
@pandurijal sure that's actually a really good idea about adding a loader, go-ahead

**Comment by Satyam1203** [comment]
@pandurijal removed his assignment, and if nobody is doing this, I would like to work on it... @Ishaan28malik

**Comment by Ishaan28malik** [comment]
@Satyam1203 sure.

**Comment by Satyam1203** [comment]
Hey @Ishaan28malik , wanted to know that should I remove node modules directory or not. It is not preferred I guess but I saw you rejected few PRs that removed it... Should I remove it or not ?

**Comment by Ishaan28malik** [comment]
> Hey @Ishaan28malik , wanted to know that should I remove node modules directory or not. It is not preferred I guess but I saw you rejected few PRs that removed it... Should I remove it or not ?

I am currently working on something , don't delete it for a while

**Comment by Satyam1203** [comment]
Okay.. Can I change class component to functional component ?
@Ishaan28malik

**Comment by Satyam1203** [comment]
I forked the repo and just saw that someone already added a loader...

**Comment by Ishaan28malik** [comment]
> I forked the repo and just saw that someone already added a loader...

It's not actually the permanent loader you can update with your enhancements and I will check. Implement that and raise a PR

**Comment by Satyam1203** [comment]
Sure @Ishaan28malik

**Comment by Satyam1203** [comment]
I've implemented the required changes in PR #19 . Do have alook @Ishaan28malik
